# Generated by Django 4.1.3 on 2022-12-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_T',
            fields=[
                ('studentID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('enrollmentDate', models.DateField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Program_T',
            fields=[
                ('programID', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=70)),
                ('department', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50, null=True)),
                ('numOfCredits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('courseType', models.CharField(max_length=15)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.program_t')),
            ],
        ),
    ]
