# Generated by Django 4.1.3 on 2022-12-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0002_student_t_program_t_course_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLO_T',
            fields=[
                ('ploID', models.AutoField(primary_key=True, serialize=False)),
                ('ploNum', models.CharField(max_length=5)),
                ('details', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.program_t')),
            ],
        ),
    ]
