# Generated by Django 4.1.3 on 2022-12-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spms3', '0004_remove_dean_t_school_remove_department_t_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASSESSMENT_T',
            fields=[
                ('AssessmentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AssessmentName', models.CharField(max_length=50)),
                ('TotalMarks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLO_T',
            fields=[
                ('CLOID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CLONum', models.CharField(max_length=50)),
                ('CLODescription', models.CharField(max_length=50)),
                ('BloomC', models.CharField(max_length=50)),
                ('BloomP', models.CharField(max_length=50)),
                ('BloomA', models.CharField(max_length=50)),
                ('COPOCorrelation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='COURSE_OUTLINE_T',
            fields=[
                ('CourseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=50)),
                ('CourseType', models.CharField(max_length=50)),
                ('CreditValue', models.CharField(max_length=50)),
                ('ContactHourOrWeek', models.CharField(max_length=50)),
                ('CourseDescription', models.CharField(max_length=50)),
                ('CourseObjective', models.CharField(max_length=50)),
                ('CourseContent', models.CharField(max_length=50)),
                ('AssessmentType', models.CharField(max_length=50)),
                ('ReferenceBook', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='COURSE_T',
            fields=[
                ('CourseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DEPARTMENT_T',
            fields=[
                ('DepartmentID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FACULTY_T',
            fields=[
                ('EmployeeID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('EmployeeType', models.CharField(max_length=2, null=True)),
                ('FEmployeeID', models.CharField(max_length=7)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PROGRAM_T',
            fields=[
                ('ProgramID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=50)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t')),
            ],
        ),
        migrations.CreateModel(
            name='SCHOOL_T',
            fields=[
                ('SchoolID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT_T',
            fields=[
                ('StudentID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.program_t')),
            ],
        ),
        migrations.CreateModel(
            name='SECTION_T',
            fields=[
                ('SectionID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SectionNum', models.IntegerField(null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t')),
                ('FEmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.faculty_t')),
            ],
        ),
        migrations.CreateModel(
            name='QUESTION_T',
            fields=[
                ('QuestionID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('QuestionNum', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=200)),
                ('Marks', models.IntegerField(null=True)),
                ('AssessmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.assessment_t')),
                ('CLOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.clo_t')),
            ],
        ),
        migrations.CreateModel(
            name='PLO_T',
            fields=[
                ('PlOID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PLONum', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=200)),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.program_t')),
            ],
        ),
        migrations.CreateModel(
            name='EVALUATION_T',
            fields=[
                ('StudentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ObtainedMarks', models.CharField(max_length=50)),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.question_t')),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='SchoolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.school_t'),
        ),
        migrations.CreateModel(
            name='DEPARTMENT_HEAD_T',
            fields=[
                ('EmployeeID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('EmployeeType', models.CharField(max_length=2, null=True)),
                ('DHEmployeeID', models.CharField(max_length=5)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DEAN_T',
            fields=[
                ('EmployeeID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('EmployeeType', models.CharField(max_length=2, null=True)),
                ('DEmployeeID', models.CharField(max_length=5)),
                ('SchoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.school_t')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course_t',
            name='ProgramID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.program_t'),
        ),
        migrations.CreateModel(
            name='COURSE_PREREQUISITE_T',
            fields=[
                ('PrerequisiteID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t')),
            ],
        ),
        migrations.CreateModel(
            name='COURSE_LESSON_T',
            fields=[
                ('Week', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Topic', models.CharField(max_length=50)),
                ('TeachingStrategy', models.CharField(max_length=50)),
                ('AssessmentStrategy', models.CharField(max_length=50)),
                ('CLOLevel', models.CharField(max_length=50)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t')),
            ],
        ),
        migrations.CreateModel(
            name='COURSE_EVALUATION_T',
            fields=[
                ('AssessmentTools', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MarksDist', models.CharField(max_length=50)),
                ('BloomCategory', models.CharField(max_length=50)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t')),
            ],
        ),
        migrations.CreateModel(
            name='COCOURSE_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoCourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t')),
            ],
        ),
        migrations.AddField(
            model_name='clo_t',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t'),
        ),
        migrations.AddField(
            model_name='clo_t',
            name='PLOID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.plo_t'),
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='SectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.section_t'),
        ),
    ]
