# Generated by Django 4.1.3 on 2022-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0007_course_outline_t_course_lesson_t_course_evaluation_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plo_t',
            name='Details',
            field=models.CharField(max_length=2000),
        ),
    ]
