# Generated by Django 4.1.3 on 2022-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0008_alter_plo_t_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_t',
            name='FEmployeeID',
        ),
    ]
