# Generated by Django 4.1.3 on 2022-12-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0011_remove_dean_t_demployeeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_head_t',
            name='DHEmployeeID',
        ),
        migrations.AddField(
            model_name='department_head_t',
            name='DepartmentID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t'),
        ),
        migrations.AlterField(
            model_name='dean_t',
            name='SchoolID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spms3.school_t'),
        ),
    ]
