# Generated by Django 4.1.3 on 2022-12-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0012_remove_department_head_t_dhemployeeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plo_t',
            old_name='PlOID',
            new_name='PLOID',
        ),
        migrations.RemoveField(
            model_name='clo_t',
            name='PLOID',
        ),
        migrations.AlterField(
            model_name='dean_t',
            name='SchoolID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spms3.school_t'),
        ),
        migrations.AlterField(
            model_name='department_head_t',
            name='DepartmentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spms3.department_t'),
        ),
        migrations.CreateModel(
            name='CLOPLO_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.clo_t')),
                ('PLOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.plo_t')),
            ],
        ),
    ]
