# Generated by Django 4.1.3 on 2022-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0013_rename_ploid_plo_t_ploid_remove_clo_t_ploid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_outline_t',
            name='CourseDept',
            field=models.CharField(default='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='course_outline_t',
            name='CourseSchool',
            field=models.CharField(default='School', max_length=100),
        ),
        migrations.AlterField(
            model_name='clo_t',
            name='CLOID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
