# Generated by Django 4.1.3 on 2022-12-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0014_course_outline_t_coursedept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_outline_t',
            name='CoursePrereq',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
