# Generated by Django 4.1.3 on 2022-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0018_remove_clo_t_ploid_clo_t_ploassessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lesson_t',
            name='Week',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
