# Generated by Django 4.1.3 on 2022-12-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0019_alter_course_lesson_t_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_outline_t',
            name='CourseCode',
        ),
        migrations.AddField(
            model_name='course_outline_t',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_outline_t',
            name='CourseID',
            field=models.ForeignKey(default='Course Code', on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t'),
        ),
    ]
