# Generated by Django 4.1.3 on 2022-12-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spms3', '0020_remove_course_outline_t_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_outline_t',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spms3.course_t'),
        ),
    ]
