# Generated by Django 4.1.3 on 2022-12-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMAS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
