# Generated by Django 4.1.3 on 2022-12-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='courseid',
            field=models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='CMAS.courseoutline'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='ploid',
            field=models.CharField(db_column='Ploid', max_length=100),
        ),
    ]
