# Generated by Django 4.1.3 on 2022-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMAS', '0004_remove_section_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clo',
            name='courseid',
        ),
        migrations.AddField(
            model_name='section',
            name='courseid',
            field=models.IntegerField(blank=True, db_column='CourseID', null=True),
        ),
    ]
