# Generated by Django 4.1.3 on 2022-12-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMAS', '0006_alter_courseevaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseevaluation',
            unique_together={('coid', 'assessmenttools')},
        ),
        migrations.AlterUniqueTogether(
            name='courselesson',
            unique_together={('coid', 'week')},
        ),
    ]
